config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    put :complete, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new,:create, :destroy]
  root 'tasks#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks, -> {includes :user}
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence:true, length: {minimum: 5}
  belongs_to :user
  belongs_to :category

  def complete!
    self.completed = true
    save
  end
  
  $completed = [
    ['Later',1],
    ['Next',2],
    ['Now',3]
  ]

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence:true ,uniqueness: true
  validates :name,  presence:true

  has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Authenticate

end

app/controllers/concerns/authenticate.rb
module Authenticate
  extend ActiveSupport::Concern
  
  included do

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]).decorate if session[:user_id].present? && User.find_by(id: session[:user_id])!=nil
    end

    def user_signed_in?
      if current_user.present?
        true
      else
        false
      end
    end

    helper_method :current_user, :user_signed_in?

  end
  
end

app/controllers/concerns/authentication.rb
module Authenticate
  extend ActiveSupport::Concern
  
  included do ||

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]).decorate if session[:user_id].present?
    end

    def user_signed_in?
      current_user.present?
    end

    helper_method :current_user, :user_signed_in?

  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by email:params[:email]
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:warning] = "Invalid password or email!"
      redirect_to root_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController



  def index
    @user = current_user
    if user_signed_in?
      @task = Task.where(user_id: @user.id).order('priority DESC')
    end

    def create_categories_array
        @categories = Category.all
        $categories = []
        @categories.each do |category|
        @one_category = []
        @one_category.push(category.category_name)
        @one_category.push(category.id)
        $categories.push(@one_category)
      end
      $categories
    end
    create_categories_array()
    @cat = Category.find(1)
  end
  
  def new

  end

  def create
    @user = current_user
    @task = @user.tasks.create(task_params)
    if @task.save
      flash[:success] = "Task save"
      redirect_to root_path
    else
      redirect_to request.referrer
      flash[:danger] = "Title not must be empty, and must be more than 5 characters"
    end

  end

  def edit
      @user = current_user
      @task = Task.find(params[:id])
  end

  def update
      @task = Task.find(params[:id])
      if @task.update(task_params)
      flash[:success] = "Task with id = #{@task.id} was updated"
      redirect_to tasks_path
      else
        redirect_to request.referrer
        flash[:danger] = "Title not must be empty, and must be more than 5 characters"
      end
      
  end

  def complete
    @task = Task.find(params[:id])
    @task.complete!
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title,:priority,:completed, :user_id, :category_id).merge(date: Time.now.strftime("%d.%m.%Y"))
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    redirect_to root_path
  end

  def new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
  private

  def user_params
    params.require(:user).permit(:email,:name,:password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="header">
  <div class="container">
    <div class="header__inner">
      <div class="header__logo"></div>
      <div class="header__links">
        <%if !user_signed_in? %>
        <div class="login__btn btn btn-light">Log In</div>
        <div class="signup__btn btn btn-dark">Sign Up</div>
       <%else%>
          <%=link_to "Log Out", session_path, method: :delete, class: 'logout__btn btn btn-danger'%>
        <%end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%=render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_new.html.erb
<div class="block" style="max-width: 425px; margin: 0 auto">
  <br>
  <h3>Please add new task!</h3>
  <br>
  <%=form_for [@user, @user.tasks.build], url: tasks_path do |f| %>
    <%=f.label :title %>
    <%=f.text_field :title, class:'form-control' %>
    <%=f.label :categories %>
    <%=f.select :category_id, $categories, {},  {class:'form-select'} %>
     <%=f.label :priority %>
    <%=f.select :priority, $completed, {},  {class:'form-select'} %>
    <%=f.label :completed %>
    <%=f.check_box :completed  %>
    <br>

    <div class="task__btn-block" style="text-align: right">
      <%= f.submit "Create task", class: 'btn btn-success' %>
    </div>

  <% end %>

<%@tasks = @cat.tasks%>
<%@tasks.each do |task| %>
<%=task.title%>
<%=@cat.category_name%>
<%end%>
<hr>

</div>

app/views/tasks/edit.html.erb
<%flash.each do |key, value|%>
<%if value!=nil && key=='danger'%>
<div class="alert alert-danger" role="alert"><%=value %></div>
<%end%>
<%end%>

<%= form_for :task, url: task_path(@task), method: :patch do |f| %>
<%=f.label :title %>
    <%=f.text_field :title, class:'form-control' %>
    <%=f.label :priority %>
    <%=f.select :priority, $completed, {},  {class:'form-select'} %>
    <%=f.label :completed %>
    <%=f.check_box :completed  %>
    <br>
    <%= f.submit "Update", class:"btn btn-primary"%>
<%end%>

app/views/tasks/index.html.erb
<%if user_signed_in? %>
  <br>
  <%# <div class="alert alert-info" role="alert"><%= "hello #{current_user.name_or_email}" %>
  <br> 

  <%if flash!=nil %>
  <%flash.each do |key, value| %>
    <br>
    <%if key == 'danger' %>
    <div class="alert alert-danger" role="alert"><%=value %></div>
    <%elsif key == 'success'%>
    <div class="alert alert-success" role="alert"><%=value %></div>
    <% end %>
    <br>
  <%end %>
  <%end %>
<b>
  <div class="task__inner">

    <div class="all_task">

      <% @task.each do |task| %>
      <%if task.completed == true%>
      <div class="task__item">
      <div class="task__title"><%=task.title %></div><br>
      <%= link_to content_tag( :div, 'edit', :class=>'btn btn-warning'), edit_task_path(task) %> 
      <%= link_to content_tag( :div, 'delete', :class=>'btn btn-danger'), task_path(task), method: :delete %> 
      </div>
      <div class="task_date"><%=task.date%></div>
      <%else%>
      <div class="task__item">
      <%=task.title %> 
      <%= link_to content_tag( :div, 'edit', :class=>'btn btn-warning'), edit_task_path(task) %> 
      <%= link_to content_tag( :div, 'delete', :class=>'btn btn-danger'), task_path(task), method: :delete %> 
      <%= link_to content_tag( :div, 'done', :class=>'btn btn-success'), complete_task_path(task), data: { method: :put } %> 
      </div>
      <div class="task_date"><%=task.date%></div>
      <%end%>
      
      <%end %>

    </div>


    <div class="add_new_task">
      <%=render 'tasks/new' %>
    </div>

  </div>

  <%end %>










<div class="modal__back">
  <div class="modal__signup">
      <span class="close__btn" aria-hidden="true">&times;</span>
    <%=render 'users/form' %>
  </div>
  <div class="modal__login">
    <span class="close__btn2" aria-hidden="true">&times;</span>
    <%=render 'sessions/form' %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="form__signup">

  <%= form_for  :user, url: users_path do |f|%>
    <%=f.label :email %>
    <%=f.email_field :email, class: 'form-control'%>
    <%=f.label :name %>
    <%=f.text_field :name, class: 'form-control' %>
    <%=f.label :password %>
    <%= f.password_field :password, class: 'form-control'%>
    <%=f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control'%>
    <div class="form__signup-btn">
      <%=f.submit "Register", class: 'btn btn-primary signup-btn'%>
    </div>
  <%end %>

</div>